// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLsQTs-hEeVHYfeySMsGUaXsOYChgVi54',
    appId: '1:574603232675:web:1bfed49e3f2da19af9c616',
    messagingSenderId: '574603232675',
    projectId: 'prestigequote-c1e0f',
    authDomain: 'prestigequote-c1e0f.firebaseapp.com',
    storageBucket: 'prestigequote-c1e0f.firebasestorage.app',
    measurementId: 'G-HMTG7X65H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASDVLAj07l9j11Hwnx4kvzu-5k6kNJaSk',
    appId: '1:574603232675:android:39c130267cde3bf8f9c616',
    messagingSenderId: '574603232675',
    projectId: 'prestigequote-c1e0f',
    storageBucket: 'prestigequote-c1e0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4HSnr0SJRsluqL3-cNyPDeUUz2F8Wnpk',
    appId: '1:574603232675:ios:0149d0b42e283265f9c616',
    messagingSenderId: '574603232675',
    projectId: 'prestigequote-c1e0f',
    storageBucket: 'prestigequote-c1e0f.firebasestorage.app',
    iosBundleId: 'com.example.prestigequote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4HSnr0SJRsluqL3-cNyPDeUUz2F8Wnpk',
    appId: '1:574603232675:ios:0149d0b42e283265f9c616',
    messagingSenderId: '574603232675',
    projectId: 'prestigequote-c1e0f',
    storageBucket: 'prestigequote-c1e0f.firebasestorage.app',
    iosBundleId: 'com.example.prestigequote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLsQTs-hEeVHYfeySMsGUaXsOYChgVi54',
    appId: '1:574603232675:web:834ecfacd742e268f9c616',
    messagingSenderId: '574603232675',
    projectId: 'prestigequote-c1e0f',
    authDomain: 'prestigequote-c1e0f.firebaseapp.com',
    storageBucket: 'prestigequote-c1e0f.firebasestorage.app',
    measurementId: 'G-SLY31N75ZB',
  );

}